spring.application.name=quizbaaz-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quizbaaz
spring.datasource.username=root
spring.datasource.password=#Bharti@2949
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
